import type { Metadata } from "next";
import { cookies } from "next/headers";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar/Navbar";
import Footer from "../components/Footer/Footer"
import LanguageProvider from "../components/LanguageProvider/LanguageProvider";
import ThemeProvider from "../components/ThemeProvider/ThemeProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: LayoutProps<"/">) {
  const cookieStore = await cookies();
  const savedLocale = cookieStore.get("partiva-locale")?.value;
  const locale = savedLocale === "en" ? "en" : "ar";

  const savedTheme = cookieStore.get("partiva-theme")?.value;
  const theme = savedTheme === "dark" ? "dark" : "light";

  return (
    <html
      lang={locale}
      dir={locale === "ar" ? "rtl" : "ltr"}
      suppressHydrationWarning
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased ${theme === "dark" ? "dark" : ""}`}
    >

      <body className="min-h-full flex flex-col bg-white text-slate-900 dark:bg-slate-950 dark:text-slate-100">
        <ThemeProvider initialTheme={theme}>
          <LanguageProvider initialLocale={locale}>
            <Navbar/>
            {children}
            <Footer/>
          </LanguageProvider>
        </ThemeProvider>

        </body>

    </html>
  );
}
