"use client";
import { Settings, Sparkles, Clock } from "lucide-react";
import Link from "next/link";
import { useLanguage } from "../LanguageProvider/LanguageProvider";
import type { PricingData } from "@/src/app/lib/pricingApi";
import { trackPricingEvent } from "@/src/app/lib/pricingAnalytics";

// SRS §21 -- Homepage Pricing Message: replaces the old plan-cards section
// with the new transaction-based pricing summary. All numbers/copy come
// from commissionConfig (CMS/config-driven, see pricingApi.ts) with a
// hardcoded fallback only used if the API is unreachable.
export default function PricingSection({ initialPricing, titleAr, titleEn, bodyAr, bodyEn }: { initialPricing: PricingData; titleAr?: string | null; titleEn?: string | null; bodyAr?: string | null; bodyEn?: string | null }){const {locale}=useLanguage(),ar=locale==="ar";const data=initialPricing;const cfg=data.commissionConfig;const copy=ar?{badge:"الأسعار",title:bodyAr?(titleAr||cfg?.headlineAr||"تسعير بسيط. بدون اشتراك شهري."):(cfg?.headlineAr||"تسعير بسيط. بدون اشتراك شهري."),description:bodyAr||cfg?.descriptionAr||"انضم إلى Partiva مجانًا وابدأ البيع عبر شبكتنا. بعدها تدفع عمولة بسيطة على مبيعاتك الناجحة فقط.",cta:cfg?.ctaTextAr||"انضم إلى Partiva مجانًا",contact:"تواصل معنا",freeLaunch:"ابدأ البيع مجانًا",freeParts:(n:number)=>`أول ${n} قطعة ناجحة`,freeDays:(n:number)=>`أول ${n} يومًا`,zeroCommission:"0% عمولة",whichever:"أيهما يأتي أولًا",or:"أو",limitedTime:"لفترة محدودة"}:{badge:"Pricing",title:bodyEn?(titleEn||cfg?.headlineEn||"Simple Pricing. No Monthly Subscription."):(cfg?.headlineEn||"Simple Pricing. No Monthly Subscription."),description:bodyEn||cfg?.descriptionEn||"Join Partiva for free and start selling through our network. After that, you pay a simple transaction commission based on your successful sales only.",cta:cfg?.ctaTextEn||"Join Partiva Free",contact:"Contact us",freeLaunch:"Start Selling for Free",freeParts:(n:number)=>`First ${n} successful parts`,freeDays:(n:number)=>`First ${n} days`,zeroCommission:"0% commission",whichever:"Whichever comes first",or:"OR",limitedTime:"Limited Time"};return <section dir={ar?"rtl":"ltr"} className="py-20" lang={locale} data-language-managed><div className="mx-auto max-w-5xl px-6"><div className="motion-text mb-10 text-center"><span className="text-sm font-semibold text-blue-600 dark:text-blue-400">{copy.badge}</span><h2 className="mt-3 text-3xl font-bold text-gray-900 sm:text-4xl dark:text-white">{copy.title}</h2><p className="mx-auto mt-4 max-w-2xl text-gray-500 dark:text-slate-400">{copy.description}</p></div>

{cfg&&<div className="motion-card motion-enter motion-delay-1 relative mx-auto max-w-3xl overflow-hidden rounded-2xl bg-[#0a1229] text-white shadow-lg"><span className="absolute end-4 top-4 inline-flex items-center gap-1.5 rounded-full bg-amber-500 px-3 py-1 text-xs font-semibold text-white shadow-sm"><Clock className="h-3.5 w-3.5"/>{copy.limitedTime}</span><div className="flex flex-col items-center gap-6 px-8 py-10 text-center"><div className="flex h-12 w-12 items-center justify-center rounded-xl bg-blue-600"><Sparkles className="h-6 w-6 text-white"/></div><h3 className="text-xl font-bold">{copy.freeLaunch}</h3><div className="flex flex-wrap items-center justify-center gap-3 text-sm"><span className="rounded-full bg-white/10 px-4 py-2 font-semibold">{copy.freeParts(cfg.freePartsLimit)}</span><span className="text-blue-300">{copy.or}</span><span className="rounded-full bg-white/10 px-4 py-2 font-semibold">{copy.freeDays(cfg.freePeriodDays)}</span></div><span className="text-2xl font-extrabold text-blue-400">{copy.zeroCommission}</span><span className="text-xs text-gray-400">{copy.whichever}</span><Link href="/register" onClick={()=>{trackPricingEvent("join_partiva_clicked");trackPricingEvent("pricing_cta_clicked",{location:"homepage"});}} className="btn-motion mt-2 inline-flex rounded-lg bg-blue-600 px-8 py-3 text-sm font-semibold text-white hover:bg-blue-700">{copy.cta}</Link></div></div>}

{data.customContact&&<div className="motion-enter motion-delay-4 mx-auto mt-8 max-w-3xl overflow-hidden rounded-2xl bg-[#0a1229] text-white shadow-lg"><div className="flex flex-col items-center gap-6 px-8 py-8 text-center md:flex-row md:justify-between md:text-right"><div className="flex items-start gap-4"><div className="flex h-12 w-12 shrink-0 items-center justify-center rounded-xl bg-blue-600"><Settings className="h-6 w-6 text-white"/></div><div><h3 className="text-xl font-bold">{(ar?data.customContact.titleAr:data.customContact.titleEn)||data.customContact.titleAr}</h3><p className="mt-2 max-w-2xl text-sm leading-6 text-gray-300">{(ar?data.customContact.descriptionAr:data.customContact.descriptionEn)||data.customContact.descriptionAr}</p></div></div><Link href="/contact" className="shrink-0 rounded-lg bg-white px-6 py-3 text-sm font-semibold text-[#0a1229]">{copy.contact}</Link></div></div>}
</div></section>}
